import Provider from '@/components/provider';
import { cn } from '@/lib/utils';
import '@/styles/tailwind.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Next.js enterprise ready',
  description: 'Generated by Hi next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn('bg-white transition-colors duration-200 dark:bg-black')}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
